import type { ReactNode } from "react";
import type { CmsHeroSettings } from "@/lib/cms/types";

export interface HeaderInternoProps {
  image?: string;
  mobileImage?: string;
  variant?: "image" | "text" | "presentation";
  hero?: CmsHeroSettings;
  eyebrow?: string;
  title?: string;
  height?: "small" | "medium" | "large";
  overlayTitle?: boolean;
  heroMenuTone?: "light" | "dark";
  heroMenuColor?: string;
  heroMenuScale?: number;
  heroLogoPositionX?: string;
  heroLogoPositionY?: string;
  heroLogoWidth?: string;
  heroLogoTabletPositionX?: string;
  heroLogoTabletPositionY?: string;
  heroLogoTabletWidth?: string;
  heroLogoMobilePositionX?: string;
  heroLogoMobilePositionY?: string;
  heroLogoMobileWidth?: string;
  heroMenuPositionY?: string;
  heroMenuTabletPositionY?: string;
  heroMenuMobilePositionY?: string;
  heroTitleImageScale?: number;
  heroTitleImageScaleTablet?: number;
  heroTitleImageScaleMobile?: number;
  heroTitleImagePositionX?: string;
  heroTitleImagePositionY?: string;
  heroTitleImagePositionXTablet?: string;
  heroTitleImagePositionYTablet?: string;
  heroTitleImagePositionXMobile?: string;
  heroTitleImagePositionYMobile?: string;
  heroTitleImageSecondaryScale?: number;
  heroTitleImageSecondaryScaleTablet?: number;
  heroTitleImageSecondaryScaleMobile?: number;
  heroTitleImageSecondaryPositionX?: string;
  heroTitleImageSecondaryPositionY?: string;
  heroTitleImageSecondaryPositionXTablet?: string;
  heroTitleImageSecondaryPositionYTablet?: string;
  heroTitleImageSecondaryPositionXMobile?: string;
  heroTitleImageSecondaryPositionYMobile?: string;
  heroTitlePositionX?: string;
  heroTitlePositionXTablet?: string;
  heroTitlePositionXMobile?: string;
  heroTitlePositionY?: string;
  heroTitlePositionYTablet?: string;
  heroTitlePositionYMobile?: string;
  heroTitleScale?: number;
  heroTitleScaleTablet?: number;
  heroTitleScaleMobile?: number;
  presentationTextPositionX?: string;
  presentationTextPositionY?: string;
  presentationTextPositionXTablet?: string;
  presentationTextPositionYTablet?: string;
  presentationTextPositionXMobile?: string;
  presentationTextPositionYMobile?: string;
  presentationTextScale?: number;
  presentationTextScaleTablet?: number;
  presentationTextScaleMobile?: number;
  presentationImagePositionX?: string;
  presentationImagePositionY?: string;
  presentationImagePositionXTablet?: string;
  presentationImagePositionYTablet?: string;
  presentationImagePositionXMobile?: string;
  presentationImagePositionYMobile?: string;
  presentationImageScale?: number;
  presentationImageScaleTablet?: number;
  presentationImageScaleMobile?: number;
  className?: string;
  children?: ReactNode;
}
